#just for tac
statistics=false
job=Update_mean_max
jobVersion=0.1
date=2016-02-05 173546238
contextName=Default
jobId=_1wx5QJNvEeWpGbupVs8Z7g
projectId=0
applyContextToChildren=false
project=SRIYAMLXIGAAPI
branch=
cmdLineVersion=6.0.1.20150908_1633
