#this is context properties
#Fri Feb 05 17:35:45 IST 2016

#Build-in context variables
host=localhost
port=3306
username=root
password=root
database=sriyaplugin
companyid=XY432126
StartDate=2016-01-01 00\:00\:00
EndDate=2016-02-04 00\:00\:00
