#this is context properties
#Fri Feb 05 17:35:38 IST 2016

#Build-in context variables
companyid=SO575859
startdate=2016-01-01
enddate=2016-02-04
host=54.88.209.139
port=3306
username=mlxitest
password=indiawin01
database=sriyaplugin
