"""
Visual-aware PDF / DOCX / HTML writers used by the Documentation Export Center.

These writers wrap the existing TMA writers in
`app.tiap.documentation.report_pack_generator` and add a single new
capability: inline-image embedding via the `asset:` markdown placeholder
defined in `app.ui.export_assets`.

Public API:

    write_pdf(path, sections, manifests)
    write_docx(path, sections, manifests)
    write_html(path, sections, manifests)
    pdf_bytes / docx_bytes / html_bytes — same, returning bytes

Where `sections: dict[title, markdown]` and
`manifests: dict[section_title, AssetManifest]`. Sections may also contain
plain markdown without any asset references — those flow through unchanged.
"""
from __future__ import annotations

import io
import os
import re
from datetime import datetime
from typing import Dict, List, Optional, Tuple

from app.ui.export_assets import (
    AssetManifest, _IMG_RE, replace_assets_inline_b64,
)


# ── HTML ────────────────────────────────────────────────────────────────────

def html_bytes(sections: Dict[str, str], manifests: Dict[str, AssetManifest],
               title: str = "Documentation") -> bytes:
    """Single-file HTML with images inlined as base64 data URIs."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    toc = "".join(
        f'<li><a href="#section-{i}">{name}</a></li>'
        for i, name in enumerate(sections.keys(), start=1)
    )
    body_parts: List[str] = []
    for i, (name, md) in enumerate(sections.items(), start=1):
        manifest = manifests.get(name) or AssetManifest(doc_type=name)
        # Inline images first, then run the regular markdown→html converter on
        # what remains. We use base64 so single-file HTML is portable.
        md_with_imgs = replace_assets_inline_b64(md, manifest)
        from app.tiap.documentation.export_utils import markdown_fragment_to_html
        # Pre-extract the figure HTML so the markdown converter doesn't mangle it.
        fig_blocks: List[str] = []

        def _stash(match):
            fig_blocks.append(match.group(0))
            return f"@@FIG_BLOCK_{len(fig_blocks) - 1}@@"
        md_clean = re.sub(r'<figure>.*?</figure>', _stash, md_with_imgs, flags=re.DOTALL)
        html_block = markdown_fragment_to_html(md_clean)
        for idx, fb in enumerate(fig_blocks):
            html_block = html_block.replace(f"@@FIG_BLOCK_{idx}@@", fb)
        body_parts.append(
            f'<section class="doc-section" id="section-{i}">'
            f'<h1>{name}</h1>{html_block}</section>'
        )
    body = "\n".join(body_parts)
    out = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{ font-family: 'Inter', Arial, sans-serif; color:#1a1a1a;
          margin:40px; line-height:1.55; max-width:1100px; }}
  .cover {{ text-align:center; padding:80px 0 40px; }}
  .cover h1 {{ font-size:32px; color:#1a3c6e; margin:0 0 8px; }}
  .cover p {{ color:#6b7280; margin:0; }}
  .toc {{ background:#f8fafc; border:1px solid #e2e8f0; padding:20px 28px;
          border-radius:10px; margin:32px 0; }}
  .toc h2 {{ margin-top:0; color:#1a3c6e; }}
  .toc ol {{ line-height:1.9; }}
  .toc a {{ color:#1d4ed8; text-decoration:none; }}
  .doc-section {{ margin-top:48px; padding-top:8px;
                  border-top:1px solid #e2e8f0; }}
  .doc-section h1 {{ color:#1a3c6e; }}
  h2 {{ color:#2563eb; }}
  pre {{ background:#f3f4f6; padding:12px; border-radius:6px;
          font-size:9pt; overflow-x:auto; }}
  figure {{ margin: 18px 0; padding:12px; background:#ffffff;
            border:1px solid #e2e8f0; border-radius:10px; text-align:center; }}
  figure img {{ max-width:100%; height:auto; }}
  figcaption {{ margin-top:6px; font-size:11px; color:#475569; font-style:italic; }}
</style></head><body>
<div class="cover">
  <h1>{title}</h1>
  <p>Generated by Talend Migration Accelerator</p>
  <p>{generated_at}</p>
</div>
<div class="toc"><h2>Table of Contents</h2><ol>{toc}</ol></div>
{body}
</body></html>"""
    return out.encode("utf-8")


# ── PDF ─────────────────────────────────────────────────────────────────────

def pdf_bytes(sections: Dict[str, str], manifests: Dict[str, AssetManifest],
              title: str = "Documentation") -> bytes:
    """Multi-page styled PDF with embedded images via reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, PageBreak,
            HRFlowable, Image as RLImage, Table, TableStyle,
        )
    except Exception as e:
        # Reportlab is a hard dep but if anything goes wrong we fall back to
        # a one-line error PDF rather than crashing the whole export flow.
        return f"PDF unavailable: {e}".encode()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )
    styles = getSampleStyleSheet()
    style_title  = ParagraphStyle("Title2",  parent=styles["Title"],   fontSize=24, textColor=colors.HexColor("#1a3c6e"), spaceAfter=12)
    style_sub    = ParagraphStyle("Sub2",    parent=styles["Normal"],  fontSize=11, textColor=colors.HexColor("#6b7280"))
    style_h1     = ParagraphStyle("H1",      parent=styles["Heading1"], fontSize=16, textColor=colors.HexColor("#1a3c6e"), spaceBefore=18, spaceAfter=8)
    style_h2     = ParagraphStyle("H2",      parent=styles["Heading2"], fontSize=13, textColor=colors.HexColor("#2563eb"), spaceBefore=12, spaceAfter=6)
    style_h3     = ParagraphStyle("H3",      parent=styles["Heading3"], fontSize=11, textColor=colors.HexColor("#374151"), spaceBefore=8,  spaceAfter=4)
    style_body   = ParagraphStyle("Body2",   parent=styles["Normal"],  fontSize=10, leading=14, spaceAfter=4)
    style_bullet = ParagraphStyle("Bullet2", parent=styles["Normal"],  fontSize=10, leading=14, leftIndent=16, spaceAfter=2)
    style_code   = ParagraphStyle("Code2",   parent=styles["Code"],    fontSize=8,  leading=12, backColor=colors.HexColor("#f3f4f6"), leftIndent=12, spaceAfter=6)
    style_capt   = ParagraphStyle("Capt",    parent=styles["Italic"],  fontSize=9,  textColor=colors.HexColor("#475569"), alignment=1, spaceAfter=8)

    story = []
    # Cover
    story.append(Spacer(1, 50 * mm))
    story.append(Paragraph(title, style_title))
    story.append(Paragraph("Generated by Talend Migration Accelerator", style_sub))
    story.append(Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M:%S"), style_sub))
    story.append(PageBreak())

    # TOC
    story.append(Paragraph("Table of Contents", style_h1))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#1a3c6e")))
    story.append(Spacer(1, 6))
    for idx, name in enumerate(sections.keys(), start=1):
        story.append(Paragraph(f"{idx}.  {name}", style_body))
    story.append(PageBreak())

    for name, md in sections.items():
        story.append(Paragraph(name, style_h1))
        story.append(HRFlowable(width="100%", color=colors.HexColor("#1a3c6e")))
        story.append(Spacer(1, 4))
        manifest = manifests.get(name) or AssetManifest(doc_type=name)
        _add_pdf_content(
            story, md, manifest, style_body, style_h2, style_h3,
            style_bullet, style_code, style_capt, RLImage, Paragraph,
            Spacer, Table, TableStyle, colors,
        )
        story.append(PageBreak())

    try:
        doc.build(story)
    except Exception as e:
        # Last-resort: still emit a minimal PDF so the user gets *something*.
        from reportlab.pdfgen import canvas as rl_canvas
        c = rl_canvas.Canvas(buf, pagesize=A4)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(60, 760, title)
        c.setFont("Helvetica", 10)
        c.drawString(60, 740, f"Render error: {e}")
        c.save()
    return buf.getvalue()


def _add_pdf_content(story, content: str, manifest: AssetManifest,
                     style_body, style_h2, style_h3, style_bullet, style_code,
                     style_capt, RLImage, Paragraph, Spacer, Table, TableStyle, colors):
    import html as html_mod
    by_key = {a.key: a for a in manifest.assets}

    lines = (content or "").splitlines()
    in_code = False
    code_lines: List[str] = []
    table_buf: List[List[str]] = []
    skipped_h1 = False

    def flush_table():
        nonlocal table_buf
        if not table_buf:
            return
        rows = [r for r in table_buf
                if not all(set(c.replace("-", "").replace(":", "").replace(" ", "")) == set() for c in r)]
        if not rows:
            table_buf = []
            return
        ncols = max(len(r) for r in rows)
        padded = [r + [""] * (ncols - len(r)) for r in rows]
        from reportlab.lib.units import mm
        from reportlab.lib.pagesizes import A4
        col_w = (A4[0] - 40 * mm) / ncols
        tbl = Table(padded, colWidths=[col_w] * ncols, repeatRows=1)
        tbl.setStyle(TableStyle([
            ("BACKGROUND",     (0, 0), (-1, 0), colors.HexColor("#1a3c6e")),
            ("TEXTCOLOR",      (0, 0), (-1, 0), colors.white),
            ("FONTNAME",       (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",       (0, 0), (-1, -1), 8),
            ("GRID",           (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",     (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 3),
        ]))
        story.append(tbl)
        story.append(Spacer(1, 6))
        table_buf = []

    for line in lines:
        # Inline image marker.
        m = _IMG_RE.search(line)
        if m and not in_code:
            flush_table()
            caption = m.group("caption")
            a = by_key.get(m.group("key"))
            if a and a.mime in ("image/png", "image/jpeg"):
                from reportlab.lib.units import mm
                from reportlab.lib.pagesizes import A4
                max_w = A4[0] - 40 * mm
                try:
                    img = RLImage(io.BytesIO(a.data))
                    iw, ih = img.imageWidth, img.imageHeight
                    if iw > max_w:
                        ratio = max_w / float(iw)
                        img.drawWidth = max_w
                        img.drawHeight = ih * ratio
                    story.append(img)
                    if caption:
                        story.append(Paragraph(html_mod.escape(caption), style_capt))
                    story.append(Spacer(1, 4))
                except Exception:
                    pass
            continue

        stripped = line.strip()
        if stripped.startswith("|") and "|" in stripped[1:]:
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            table_buf.append(cells)
            continue
        else:
            flush_table()

        if stripped.startswith("```"):
            if in_code:
                if code_lines:
                    story.append(Paragraph("<br/>".join(html_mod.escape(l) for l in code_lines), style_code))
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue

        if not skipped_h1 and stripped.startswith("# "):
            skipped_h1 = True
            continue
        if stripped:
            skipped_h1 = True

        if stripped.startswith("# "):
            story.append(Paragraph(html_mod.escape(stripped[2:]), style_h2))
        elif stripped.startswith("## "):
            story.append(Paragraph(html_mod.escape(stripped[3:]), style_h2))
        elif stripped.startswith("### "):
            story.append(Paragraph(html_mod.escape(stripped[4:]), style_h3))
        elif stripped.startswith("- "):
            story.append(Paragraph(f"• &nbsp;{html_mod.escape(stripped[2:])}", style_bullet))
        elif stripped == "":
            story.append(Spacer(1, 4))
        else:
            story.append(Paragraph(html_mod.escape(stripped), style_body))

    flush_table()
    if in_code and code_lines:
        story.append(Paragraph("<br/>".join(html_mod.escape(l) for l in code_lines), style_code))


# ── DOCX ────────────────────────────────────────────────────────────────────

def docx_bytes(sections: Dict[str, str], manifests: Dict[str, AssetManifest],
               title: str = "Documentation") -> bytes:
    from docx import Document
    from docx.shared import Pt, Inches

    document = Document()
    document.core_properties.title = title
    document.core_properties.subject = "Talend Migration Accelerator"
    styles = document.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"].font.size = Pt(10)

    document.add_heading(title, level=0)
    document.add_paragraph("Generated by Talend Migration Accelerator")
    document.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    document.add_page_break()

    document.add_heading("Table of Contents", level=1)
    for idx, name in enumerate(sections.keys(), start=1):
        document.add_paragraph(f"{idx}. {name}", style="List Number")

    for name, md in sections.items():
        document.add_page_break()
        document.add_heading(name, level=1)
        manifest = manifests.get(name) or AssetManifest(doc_type=name)
        _add_docx_content(document, md, manifest, Inches)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def _add_docx_content(document, content: str, manifest: AssetManifest, Inches):
    from docx.shared import Pt
    by_key = {a.key: a for a in manifest.assets}

    lines = (content or "").splitlines() or ["No content generated."]
    in_code = False
    code_lines: List[str] = []
    skipped_h1 = False

    for line in lines:
        m = _IMG_RE.search(line)
        if m and not in_code:
            caption = m.group("caption")
            a = by_key.get(m.group("key"))
            if a and a.mime in ("image/png", "image/jpeg"):
                try:
                    document.add_picture(io.BytesIO(a.data), width=Inches(6.0))
                    if caption:
                        cp = document.add_paragraph(caption)
                        run = cp.runs[0]
                        run.italic = True
                        run.font.size = Pt(9)
                except Exception:
                    pass
            continue

        stripped = line.strip()
        if stripped.startswith("```"):
            if in_code:
                if code_lines:
                    p = document.add_paragraph()
                    r = p.add_run("\n".join(code_lines))
                    r.font.name = "Courier New"
                    r.font.size = Pt(9)
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue

        if not skipped_h1 and stripped.startswith("# "):
            skipped_h1 = True
            continue
        if stripped:
            skipped_h1 = True

        if stripped.startswith("# "):
            document.add_heading(stripped[2:].strip(), level=1)
        elif stripped.startswith("## "):
            document.add_heading(stripped[3:].strip(), level=2)
        elif stripped.startswith("### "):
            document.add_heading(stripped[4:].strip(), level=3)
        elif stripped.startswith("- "):
            document.add_paragraph(stripped[2:].strip(), style="List Bullet")
        elif stripped:
            document.add_paragraph(stripped)
        else:
            document.add_paragraph("")

    if in_code and code_lines:
        p = document.add_paragraph()
        r = p.add_run("\n".join(code_lines))
        r.font.name = "Courier New"
        r.font.size = Pt(9)


# ── File-writing convenience wrappers ────────────────────────────────────────

def write_pdf(path: str, sections, manifests, title="Documentation") -> str:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        f.write(pdf_bytes(sections, manifests, title))
    return path


def write_docx(path: str, sections, manifests, title="Documentation") -> str:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        f.write(docx_bytes(sections, manifests, title))
    return path


def write_html(path: str, sections, manifests, title="Documentation") -> str:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        f.write(html_bytes(sections, manifests, title))
    return path
