class StudioImportGuide:

    def generate(self):

        return [

            {
                "step": 1,

                "title":
                    "Open Talend 8 Studio",

                "details":
                    "Launch Talend Studio 8 "
                    "with a clean workspace."
            },

            {
                "step": 2,

                "title":
                    "Import Original Repository",

                "details":
                    "Use the original Talend "
                    "Open Studio export ZIP."
            },

            {
                "step": 3,

                "title":
                    "Allow Migration Tasks",

                "details":
                    "Talend Studio will execute "
                    "internal migration tasks."
            },

            {
                "step": 4,

                "title":
                    "Review Invalid Items",

                "details":
                    "Review contexts, routines, "
                    "and unsupported components."
            },

            {
                "step": 5,

                "title":
                    "Apply Remediation",

                "details":
                    "Use migration guidance "
                    "generated by this platform."
            },

            {
                "step": 6,

                "title":
                    "Re-export Migrated Repository",

                "details":
                    "Export migrated repository "
                    "from Talend 8 Studio."
            }
        ]