
from app.ai.llm_engine import ask_ollama
from app.tiap.profiling.component_profiler import ComponentProfiler


DEFAULT_COMPONENT_RECOMMENDATION_PROMPT = """
You are a Talend 8 and Talend Cloud migration architect.

Analyze this repository-level component intelligence summary. Do not ask for source data rows.

Custom and unknown components:
{custom_unknown_summary}

Deprecated components:
{deprecated_summary}

Provide:
1. Migration risk summary
2. Replacement or validation recommendations
3. Remediation sequencing
4. Talend Cloud readiness considerations

Keep the response concise and action-oriented.
"""


def _component_summary(rows, limit=12):
    return [
        {
            "component": row.get("component"),
            "classification": row.get("classification"),
            "usage_count": row.get("usage_count", 0),
            "risk": row.get("risk"),
            "jobs_impacted": len(row.get("jobs_impacted", [])),
            "recommendation": row.get("recommendation"),
        }
        for row in rows[:limit]
    ]


def _fallback_component_recommendation(profile):
    custom_unknown = profile.get("custom_components", []) + profile.get("unknown_components", [])
    deprecated = profile.get("deprecated_components", [])
    lines = ["**Component Migration Recommendation**"]

    if deprecated:
        lines.append(
            f"- Replace {len(deprecated)} deprecated component type(s) before migration validation."
        )
    if custom_unknown:
        high_risk = [row for row in custom_unknown if row.get("risk") == "HIGH"]
        lines.append(
            f"- Validate {len(custom_unknown)} custom/unknown component type(s) in the target Talend runtime."
        )
        if high_risk:
            lines.append(
                f"- Prioritize {len(high_risk)} high-risk component type(s) because they affect multiple jobs."
            )
    lines.append("- Run Talend 8 Studio import, then execute regression tests for impacted jobs.")
    lines.append("- For Talend Cloud, verify runtime dependencies, libraries, and unsupported component availability.")
    lines.append("\n_Note: Generated by built-in rule engine. Enable Ollama for LLM-powered guidance._")
    return "\n".join(lines)


def build_component_recommendation_prompt(profile, prompt_template: str = None):
    custom_unknown = profile.get("custom_components", []) + profile.get("unknown_components", [])
    deprecated = profile.get("deprecated_components", [])
    template = prompt_template or DEFAULT_COMPONENT_RECOMMENDATION_PROMPT
    values = {
        "custom_unknown_summary": _component_summary(custom_unknown),
        "deprecated_summary": _component_summary(deprecated),
    }
    try:
        return template.format(**values)
    except Exception:
        return DEFAULT_COMPONENT_RECOMMENDATION_PROMPT.format(**values)


def _generate_component_ai_recommendation(profile, use_ollama=True, prompt_template: str = None):
    custom_unknown = profile.get("custom_components", []) + profile.get("unknown_components", [])
    deprecated = profile.get("deprecated_components", [])

    if not custom_unknown and not deprecated:
        return (
            "No custom, unknown, or deprecated components were detected. "
            "Continue with standard Talend 8 import validation and regression testing."
        )

    if not use_ollama:
        return _fallback_component_recommendation(profile)

    prompt = build_component_recommendation_prompt(profile, prompt_template)
    return ask_ollama(prompt, use_ollama=use_ollama)


def analyze_custom_components(all_jobs, use_ollama: bool = True, prompt_template: str = None):

    profile = ComponentProfiler().profile(all_jobs)
    return {
        "standard_components": profile["standard_components"],
        "deprecated_components": profile["deprecated_components"],
        "custom_components": profile["custom_components"] + profile["unknown_components"],
        "unknown_components": profile["unknown_components"],
        "component_distribution": profile["component_distribution"],
        "top_components": profile["top_components"],
        "migration_risk": profile["migration_risk"],
        "total_custom": len(profile["custom_components"]) + len(profile["unknown_components"]),
        "impacted_jobs": profile["impacted_jobs"],
        "ai_recommendation": _generate_component_ai_recommendation(
            profile,
            use_ollama=use_ollama,
            prompt_template=prompt_template,
        ),
    }
